"""add unique constraints on client cin and ice

Revision ID: 112a861157aa
Revises: efa951d379dd
Create Date: 2026-07-15 11:03:15.980919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '112a861157aa'
down_revision: Union[str, Sequence[str], None] = 'efa951d379dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_client_cin', 'client', ['cin'], unique=True, postgresql_where=sa.text('cin IS NOT NULL'))
    op.create_index('idx_client_ice', 'client', ['ice'], unique=True, postgresql_where=sa.text('ice IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_client_ice', table_name='client', postgresql_where=sa.text('ice IS NOT NULL'))
    op.drop_index('idx_client_cin', table_name='client', postgresql_where=sa.text('cin IS NOT NULL'))
    # ### end Alembic commands ###
