"""initial schema

Revision ID: efa951d379dd
Revises: 
Create Date: 2026-07-13 09:34:47.077282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efa951d379dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banque_agence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('rib', sa.String(length=34), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compagnie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('utilisateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('keycloak_id', sa.String(length=255), nullable=True),
    sa.Column('role', postgresql.ENUM('utilisateur', 'super_administrateur', name='role_utilisateur'), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('keycloak_id')
    )
    op.create_table('bordereau_reversement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_bordereau', sa.String(length=30), nullable=False),
    sa.Column('compagnie_id', sa.Integer(), nullable=False),
    sa.Column('periode_debut', sa.Date(), nullable=False),
    sa.Column('periode_fin', sa.Date(), nullable=False),
    sa.Column('montant_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('commission_totale', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('statut', postgresql.ENUM('brouillon', 'valide', 'reverse', name='statut_bordereau_reversement'), nullable=False),
    sa.Column('date_generation', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('valide_par', sa.Integer(), nullable=True),
    sa.Column('date_validation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['compagnie_id'], ['compagnie.id'], ),
    sa.ForeignKeyConstraint(['valide_par'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_bordereau')
    )
    op.create_table('bordereau_versement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_bordereau', sa.String(length=30), nullable=False),
    sa.Column('banque_agence_id', sa.Integer(), nullable=False),
    sa.Column('date_bordereau', sa.Date(), nullable=False),
    sa.Column('statut', postgresql.ENUM('brouillon', 'genere', 'verse', name='statut_bordereau_versement'), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['banque_agence_id'], ['banque_agence.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_bordereau')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', postgresql.ENUM('particulier', 'entreprise', name='type_client'), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('pays', sa.String(length=100), nullable=True),
    sa.Column('statut', postgresql.ENUM('actif', 'prospect', 'vip', name='statut_client'), nullable=False),
    sa.Column('charge_de_compte_id', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('cin', sa.String(length=20), nullable=True),
    sa.Column('nom', sa.String(length=150), nullable=True),
    sa.Column('prenom', sa.String(length=150), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('sexe', sa.String(length=10), nullable=True),
    sa.Column('profession', sa.String(length=150), nullable=True),
    sa.Column('raison_sociale', sa.String(length=255), nullable=True),
    sa.Column('ice', sa.String(length=30), nullable=True),
    sa.Column('responsable', sa.String(length=150), nullable=True),
    sa.Column('banque_principale', sa.String(length=150), nullable=True),
    sa.Column('rib', sa.String(length=34), nullable=True),
    sa.CheckConstraint("type != 'entreprise' OR (raison_sociale IS NOT NULL AND ice IS NOT NULL)", name='chk_client_entreprise'),
    sa.CheckConstraint("type != 'particulier' OR (cin IS NOT NULL AND nom IS NOT NULL AND prenom IS NOT NULL)", name='chk_client_particulier'),
    sa.ForeignKeyConstraint(['charge_de_compte_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_cible', sa.String(length=100), nullable=False),
    sa.Column('enregistrement_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('auteur_id', sa.Integer(), nullable=True),
    sa.Column('date_action', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ancienne_valeur', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nouvelle_valeur', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['auteur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_journal_audit_cible', 'journal_audit', ['table_cible', 'enregistrement_id'], unique=False)
    op.create_table('produit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compagnie_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['compagnie_id'], ['compagnie.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('bareme_commission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compagnie_id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=True),
    sa.Column('taux_commission', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['compagnie_id'], ['compagnie.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encaissement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('mode_paiement', postgresql.ENUM('especes', 'cheque', 'virement', name='mode_paiement'), nullable=False),
    sa.Column('montant', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date_encaissement', sa.Date(), nullable=False),
    sa.Column('statut', postgresql.ENUM('enregistre', 'rapproche_banque', 'rejete', name='statut_encaissement'), nullable=False),
    sa.Column('cheque_banque', sa.String(length=150), nullable=True),
    sa.Column('cheque_numero', sa.String(length=50), nullable=True),
    sa.Column('cheque_echeance', sa.Date(), nullable=True),
    sa.Column('virement_banque', sa.String(length=150), nullable=True),
    sa.Column('virement_rib', sa.String(length=34), nullable=True),
    sa.Column('virement_reference', sa.String(length=100), nullable=True),
    sa.Column('enregistre_par', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['enregistre_par'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garantie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('parametres', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['produit_id'], ['produit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produit_id', 'code')
    )
    op.create_table('lien_familial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('souscripteur_id', sa.Integer(), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=False),
    sa.Column('lien_parente', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['membre_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['souscripteur_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('souscripteur_id', 'membre_id')
    )
    op.create_table('piece_justificative_requise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('obligatoire', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['produit_id'], ['produit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('police',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_police', sa.String(length=30), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('statut', postgresql.ENUM('en_attente_effet', 'en_vigueur', 'suspendu', 'resilie', name='statut_police'), nullable=False),
    sa.Column('date_effet', sa.Date(), nullable=False),
    sa.Column('date_echeance', sa.Date(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_police')
    )
    op.create_table('avenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('police_id', sa.Integer(), nullable=False),
    sa.Column('type_avenant', postgresql.ENUM('affaire_nouvelle', 'renouvellement', 'modification', 'suspension', 'resiliation', name='type_avenant'), nullable=False),
    sa.Column('motif', sa.String(length=255), nullable=True),
    sa.Column('date_effet', sa.Date(), nullable=False),
    sa.Column('statut', postgresql.ENUM('brouillon', 'valide', 'annule', name='statut_avenant'), nullable=False),
    sa.Column('valide_par', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_validation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['police_id'], ['police.id'], ),
    sa.ForeignKeyConstraint(['valide_par'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bordereau_versement_ligne',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bordereau_versement_id', sa.Integer(), nullable=False),
    sa.Column('encaissement_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['bordereau_versement_id'], ['bordereau_versement.id'], ),
    sa.ForeignKeyConstraint(['encaissement_id'], ['encaissement.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bordereau_versement_id', 'encaissement_id')
    )
    op.create_table('risque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('police_id', sa.Integer(), nullable=False),
    sa.Column('type_risque', sa.String(length=50), nullable=False),
    sa.Column('attributs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['police_id'], ['police.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('police_garantie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('police_id', sa.Integer(), nullable=False),
    sa.Column('risque_id', sa.Integer(), nullable=True),
    sa.Column('garantie_id', sa.Integer(), nullable=False),
    sa.Column('montant_prime', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['garantie_id'], ['garantie.id'], ),
    sa.ForeignKeyConstraint(['police_id'], ['police.id'], ),
    sa.ForeignKeyConstraint(['risque_id'], ['risque.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('police_id', 'risque_id', 'garantie_id')
    )
    op.create_table('quittance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_quittance', sa.String(length=30), nullable=False),
    sa.Column('police_id', sa.Integer(), nullable=False),
    sa.Column('avenant_id', sa.Integer(), nullable=False),
    sa.Column('periode_debut', sa.Date(), nullable=False),
    sa.Column('periode_fin', sa.Date(), nullable=False),
    sa.Column('prime_nette', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('taxes', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('timbres', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('accessoires', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('prime_ttc', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('statut', postgresql.ENUM('emise', 'reglee_partiellement', 'reglee', 'annulee', name='statut_quittance'), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avenant_id'], ['avenant.id'], ),
    sa.ForeignKeyConstraint(['police_id'], ['police.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_quittance')
    )
    op.create_table('bordereau_reversement_ligne',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bordereau_reversement_id', sa.Integer(), nullable=False),
    sa.Column('quittance_id', sa.Integer(), nullable=False),
    sa.Column('prime_nette_reversee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission_calculee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['bordereau_reversement_id'], ['bordereau_reversement.id'], ),
    sa.ForeignKeyConstraint(['quittance_id'], ['quittance.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bordereau_reversement_id', 'quittance_id')
    )
    op.create_table('dossier_recouvrement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quittance_id', sa.Integer(), nullable=False),
    sa.Column('statut', postgresql.ENUM('ouvert', 'en_relance', 'mise_en_demeure', 'suspendu', 'resilie', 'regularise', name='statut_dossier_recouv'), nullable=False),
    sa.Column('date_ouverture', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('date_cloture', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['quittance_id'], ['quittance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encaissement_quittance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encaissement_id', sa.Integer(), nullable=False),
    sa.Column('quittance_id', sa.Integer(), nullable=False),
    sa.Column('montant_affecte', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['encaissement_id'], ['encaissement.id'], ),
    sa.ForeignKeyConstraint(['quittance_id'], ['quittance.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('encaissement_id', 'quittance_id')
    )
    op.create_table('relance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossier_recouvrement_id', sa.Integer(), nullable=False),
    sa.Column('type_relance', postgresql.ENUM('amiable', 'mise_en_demeure', name='type_relance'), nullable=False),
    sa.Column('date_relance', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=True),
    sa.Column('resultat', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['dossier_recouvrement_id'], ['dossier_recouvrement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relance')
    op.drop_table('encaissement_quittance')
    op.drop_table('dossier_recouvrement')
    op.drop_table('bordereau_reversement_ligne')
    op.drop_table('quittance')
    op.drop_table('police_garantie')
    op.drop_table('risque')
    op.drop_table('bordereau_versement_ligne')
    op.drop_table('avenant')
    op.drop_table('police')
    op.drop_table('piece_justificative_requise')
    op.drop_table('lien_familial')
    op.drop_table('garantie')
    op.drop_table('encaissement')
    op.drop_table('bareme_commission')
    op.drop_table('produit')
    op.drop_index('idx_journal_audit_cible', table_name='journal_audit')
    op.drop_table('journal_audit')
    op.drop_table('client')
    op.drop_table('bordereau_versement')
    op.drop_table('bordereau_reversement')
    op.drop_table('utilisateur')
    op.drop_table('compagnie')
    op.drop_table('banque_agence')
    # ### end Alembic commands ###
